name: Comment rollup
description: Rolls up status updates into a single comment for ease of copying
inputs:
  label:
    description: Label of issues to rollup
    required: false
    default: "Weekly Update Notes"
  issue_number:
    description: Issue to rollup
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.issue_number }}
    - ${{ inputs.label }}