name: Comment rollup
description: Rolls up status updates into a single comment for ease of copying
inputs:
  label:
    description: Label of issues or discussions to rollup
    required: false
  number:
    description: Issue or discussion number to rollup
    required: false
  token:
    description: Github token
    required: true
  type:
    description: Type of issue or discussion to rollup
    required: true
    default: issue
  link_to_doc:
    description: Whether to create and link to a .docx file
    required: false
outputs:
  body:
    description: The resulting issue body
runs:
  using: 'node20'
  main: 'dist/index.js'