name: Comment rollup
description: Rolls up status updates into a single comment for ease of copying
inputs:
  label:
    description: Label of issues to rollup
    required: false
  issue_number:
    description: Issue to rollup
    required: true
  token:
    description: Github token
    required: true
outputs:
  body:
    description: The resulting issue body
runs:
  using: 'node16'
  main: 'index.js'